name: Deployment
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: beta
    env:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}
      NAME: deploy-server
    steps:
      - name: create key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ env.KEY }}" > ~/.ssh/${{ env.NAME }}.key
          sudo chmod 600 ~/.ssh/${{ env.NAME }}.key
        shell: bash
      - name: Scan the public ssh host keys
        run: ssh-keyscan -H ${{ env.HOST }} >> ~/.ssh/known_hosts
        shell: bash
      - name: Create SSH config
        run: |
          cat >>~/.ssh/config <<END
          Host ${{ env.NAME }}
            HostName ${{ env.HOST }}
            Port ${{ env.PORT }}
            User ${{ env.USER }}
            IdentityFile ~/.ssh/${{ env.NAME }}.key
          END
        shell: bash
      - name: run commands
        run: ssh ${{env.NAME}} << END
              mkdir hello-world
              cd hello-world
              echo "hey hi" > index.html
              cat index.html
            END